version: "3.8"
services:
  app:
    build: .
    restart: always
  db:
    image: "postgres:16.2-alpine3.19"
    restart: always
    environment:
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_USER=exampleuser
    expose:
      - 5432
    ports:
      - "5432:5432"
    # volumes:
    #   -