services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev # target stage to build, CHANGE to prod for production
      args:
        - DEV=true
    restart: always
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes: # remove after testing
      - .:/app
  db:
    image: "postgres:16.2-alpine3.19"
    restart: always
    environment:
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_USER=exampleuser
    expose:
      - 5432
    ports:
      - "5432:5432"
    # volumes:
    #   -